Resources:
  BoltLambdaRoleFDF606D6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Bolt Python basic role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: bolt_python_lambda_invocation
    Metadata:
      aws:cdk:path: ApiLambdaStack/BoltLambdaRole/Resource
  BoltLambdaRoleDefaultPolicy6A52FD9F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Queue4A7E3555
                - Arn
        Version: "2012-10-17"
      PolicyName: BoltLambdaRoleDefaultPolicy6A52FD9F
      Roles:
        - Ref: BoltLambdaRoleFDF606D6
    Metadata:
      aws:cdk:path: ApiLambdaStack/BoltLambdaRole/DefaultPolicy/Resource
  LambdaFunctionBF21E41F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 6b0fd4818b79aeb1484c03570918232c77467831fdb2e4371e1c7e4d4ac73fe3.zip
      Role:
        Fn::GetAtt:
          - BoltLambdaRoleFDF606D6
          - Arn
      Environment:
        Variables:
          OPENAI_API_KEY: XXX
          SLACK_BOT_TOKEN: XXX
          SLACK_SIGNING_SECRET: XXX
      Handler: lambda_handler.handler
      Runtime: python3.9
      Timeout: 120
    DependsOn:
      - BoltLambdaRoleDefaultPolicy6A52FD9F
      - BoltLambdaRoleFDF606D6
    Metadata:
      aws:cdk:path: ApiLambdaStack/LambdaFunction/Resource
      aws:asset:path: /Users/charlie/freedom/aws_slack_app/cdk.out/asset.6b0fd4818b79aeb1484c03570918232c77467831fdb2e4371e1c7e4d4ac73fe3
      aws:asset:is-bundled: true
      aws:asset:property: Code
  RestAPIRoleA3B4EFA3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSLambda_FullAccess
    Metadata:
      aws:cdk:path: ApiLambdaStack/RestAPIRole/Resource
  ApiGW45519054:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: slack
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Resource
  ApiGWCloudWatchRole51A9A431:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/CloudWatchRole/Resource
  ApiGWAccountF46C4EC5:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - ApiGWCloudWatchRole51A9A431
          - Arn
    DependsOn:
      - ApiGW45519054
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Account
  ApiGWDeployment621CA0B034f882f9ee49fc26a0a9300917352b54:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ApiGW45519054
      Description: Automatically created by the RestApi construct
    DependsOn:
      - ApiGWeventsPOST099D90D1
      - ApiGWevents2E512E23
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Deployment/Resource
  ApiGWDeploymentStageprodDFD8EC11:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: ApiGW45519054
      DeploymentId:
        Ref: ApiGWDeployment621CA0B034f882f9ee49fc26a0a9300917352b54
      StageName: prod
    DependsOn:
      - ApiGWAccountF46C4EC5
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/DeploymentStage.prod/Resource
  ApiGWevents2E512E23:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGW45519054
          - RootResourceId
      PathPart: events
      RestApiId:
        Ref: ApiGW45519054
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Default/events/Resource
  ApiGWeventsPOSTApiPermissionApiLambdaStackApiGW3D0DB47FPOSTevents0C26588B:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionBF21E41F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGW45519054
            - /
            - Ref: ApiGWDeploymentStageprodDFD8EC11
            - /POST/events
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Default/events/POST/ApiPermission.ApiLambdaStackApiGW3D0DB47F.POST..events
  ApiGWeventsPOSTApiPermissionTestApiLambdaStackApiGW3D0DB47FPOSTevents2F74C5CF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionBF21E41F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGW45519054
            - /test-invoke-stage/POST/events
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Default/events/POST/ApiPermission.Test.ApiLambdaStackApiGW3D0DB47F.POST..events
  ApiGWeventsPOST099D90D1:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: ApiGWevents2E512E23
      RestApiId:
        Ref: ApiGW45519054
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - LambdaFunctionBF21E41F
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ApiLambdaStack/ApiGW/Default/events/POST/Resource
  DeadLetterQueue9F481546:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ApiLambdaStack/DeadLetterQueue/Resource
  Queue4A7E3555:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue9F481546
            - Arn
        maxReceiveCount: 4
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ApiLambdaStack/Queue/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VQ0W7CMAz8lr6ngQ4JaW8roL1NY+wDUEi94jVNsiYRqqL++9ykiO3p7iyf7fMT3255rApxc6VsulLhhcdPL2THqHSOKHoeT0YB23/phEejUI6zzGxibnMWzoF3vJ6BNN8F2YHfCQdMif7SCB7J8Bq09Gh0MsPQo3OkJiYstsLDTYy0C5yvLaZ1D1pLaYL27ABWmbEHolT9o+jkNt2YCVlNGCSkC+5imZn5G/iraeZSZhTjx/H4ESCkxkSm6WFO2ebpqNu54T14G/y/mcT3RjfoU6qqFMpeBV8XL8t3VzPmf5R2pK16aTkmcX/PxLJebXi15s/Ft0MsB4qPPfBTxl+N/wLmuAEAAA==
    Metadata:
      aws:cdk:path: ApiLambdaStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  ApiGWEndpointBE5359D4:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ApiGW45519054
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: ApiGWDeploymentStageprodDFD8EC11
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

