display_information:
  name: Bounce
  description: ChatGPT for Slack
  background_color: "#000000"
features:
  bot_user:
    display_name: Bounce
    always_online: true
oauth_config:
  redirect_urls:
    - https://22cv6vylhfcady2rsmzeeru53e0jatwy.lambda-url.us-east-1.on.aws
  scopes:
    user:
      - channels:history
      - groups:history
      - im:history
      - mpim:history
    bot:
      - app_mentions:read
      - channels:history
      - channels:join
      - channels:read
      - chat:write
      - chat:write.customize
      - commands
      - emoji:read
      - groups:history
      - groups:read
      - im:history
      - im:read
      - incoming-webhook
      - links:read
      - metadata.message:read
      - mpim:history
      - mpim:read
      - reactions:read
      - usergroups:read
      - users.profile:read
      - users:read
      - users:read.email
      - users:write
settings:
  event_subscriptions:
    request_url: https://22cv6vylhfcady2rsmzeeru53e0jatwy.lambda-url.us-east-1.on.aws
    user_events:
      - message.app_home
      - message.channels
      - message.groups
      - message.im
      - message.mpim
    bot_events:
      - app_home_opened
      - app_mention
      - message.channels
      - message.im
      - message.mpim
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false

